config/routes.rb
Rails.application.routes.draw do
root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

# Teacher
#show
get 'teachers/:id', to: 'teachers#show', as: 'show_teacher'

# Student
#show
get 'students/:id', to: 'students#show', as: 'show_student'
#index
get 'teachers/:teacher_id/students', to: 'students#index', as: 'student_index'

# Lesson
#index
get 'students/:student_id/lessons', to: 'lessons#index', as: 'lessons'
#create
post 'students/:student_id/lessons', to: 'lessons#create'
#new
get 'students/:student_id/lessons/new', to: 'lessons#new', as: 'new_lesson'
#edit
get 'lessons/:id', to: 'lessons#edit', as: 'edit_lesson'
#update
patch 'lessons/:id', to: 'lessons#update', as: 'lesson'
#destroy
delete 'lessons/:id', to: 'lessons#delete'

# Assignment
#index
get 'lessons/:lesson_id/assignments', to: 'assignments#index', as: 'assignments'
#create
post 'lessons/:lesson_id/assignments', to: 'assignments#create'
#practice
get 'lessons/:lesson_id/practice', to: 'assignments#practice', as: 'practice'
#new
get 'lessons/:lesson_id/assignments/new', to: 'assignments#new', as: 'new_assignment'
#play
patch 'assignments/:id/play', to: 'assignments#play', as: 'played'
#edit
get 'assignments/:id', to: 'assignments#edit', as: 'edit_assignment'
#update
put 'assignments/:id', to: 'assignments#update', as: 'assignment'
#delete
delete 'assignments/:id', to: 'assignments#destroy', as: 'delete_assignment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id            :integer          not null, primary key
#  book          :string           not null
#  title         :string
#  page          :integer
#  per_day       :integer
#  days_per_week :integer
#  notes         :text
#  plays         :integer
#  lesson_id     :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Assignment < ApplicationRecord
	belongs_to :lesson
	validates_presence_of :book
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :verify_teacher, except: [:index, :practice]
	before_action :lesson_by_id, only: [:index, :practice, :new, :create]
	before_action :assignment_by_id, only: [:play, :edit, :update, :destroy]
  
  def index
  	@assignments = @lesson.assignments
    @student = User.find(@lesson.user_id)
  end

  def practice
  	@assignments = @lesson.assignments
  end

  def new
  	@assignment = Assignment.new
  end

  def create
  	@assignment = @lesson.assignments.new(assignment_params)

  	if @assignment.save
  		redirect_to assignments_path(@lesson)
  	else
  		render :new
  	end
  end

  def play
    plays = @assignment.plays.to_i + 1
    @assignment.update(plays: plays)
    redirect_to assignments_path(@assignment.lesson_id)
  end

  def edit
  end

  def update

  	if @assignment.update(assignment_params)
  		redirect_to assignments_path(@assignment.lesson_id)
  	else
  		render :edit
  	end
  end

  def destroy
	@assignment.destroy
	redirect_to assignments_path(@assignment.lesson_id)
  end
  		
  private

  def assignment_params
  	params.require(:assignment).permit(:book, :title, :page, :per_day, :days_per_week, :notes, :plays)
  end

  def lesson_by_id
  	@lesson = Lesson.find(params[:lesson_id])
  end

  def assignment_by_id
  	@assignment = Assignment.find(params[:id])
  end

  def verify_teacher
    if current_user.student?
      redirect_to lessons_path(current_user)
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/edit.html.erb
<h1>Assignments#edit</h1>
<p>Find me in app/views/assignments/edit.html.erb</p>

app/views/assignments/index.html.erb
<h1>Lesson for <%= @student.first_name %> <%= @student.last_name %> on <%= @lesson.lesson_date %> </h1>

<% if current_user.teacher? %> 
	<%= button_to 'New Assignment', new_assignment_path(@lesson), class: 'btn', method: :get %>
<% end %>
<ul>
	<% @assignments.each do |assignment| %>
	<div class='card-panel row valign-wrapper'>
		<div class='col s12 m10'>
			<li>
				<h4>
					<%= "#{assignment.book}" %>
					<%= (", #{assignment.title}") if assignment.title =~ /\S/ %>
					<%= (", Pg #{assignment.page}") if assignment.page %>
				</h4>
				<%= "Reminders: #{assignment.notes}" if assignment.notes =~ /\S/ %> <br>
				<%= "Goal per Day: #{assignment.per_day}" if assignment.per_day %>
				<%= "|| Goal Days per Week: #{assignment.days_per_week}" if assignment.days_per_week %>
				<%= "|| Plays so far: #{assignment.plays.to_i}" %>
			</li>
		</div>
		<div class="col s12 m2 valign" >
			<%= button_to 'Played!', played_path(assignment), method: :patch, class: "btn-large" %>
		</div>
	</div>
	<% end %>
</ul>
<hr>
<%= link_to 'Back to Lessons', lessons_path(@student), class: 'btn'%>

app/views/assignments/new.html.erb
<% if @assignment.errors.any? %>
	<ul>
		<% @assignment.errors.full_messages.each do |error| %>
			<li> <%= error %> </li>
		<% end %>
	</ul>
<% end %>

<h1>New Assignment</h1>

<%= form_for @assignment do |f| %>

	<%= f.label :book %>
	<%= f.text_field :book, required: true %>

	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :page %>
	<%= f.number_field :page %>


	<%= f.label :per_day %>
	<%= f.number_field :per_day, placeholder: 'How many plays per day?' %>


	<%= f.label :days_per_week %>
	<%= f.number_field :days_per_week, placeholder: 'How many practice days per week?' %>


	<%= f.label :notes %>
	<%= f.text_area :notes, class: 'materialize-textarea' %>

	<%= f.submit 'Submit', class: 'btn' %>

<% end %>

app/views/assignments/practice.html.erb
<h1>Assignments#practice</h1>
<p>Find me in app/views/assignments/practice.html.erb</p>