config/routes.rb
Rails.application.routes.draw do
root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

# Teacher
#show
get 'teachers/:id', to: 'teachers#show', as: 'show_teacher'

# Student
#show
get 'students/:id', to: 'students#show', as: 'show_student'
#index
get 'teachers/:teacher_id/students', to: 'students#index', as: 'student_index'

# Lesson
#index
get 'students/:student_id/lessons', to: 'lessons#index', as: 'lessons'
#create
post 'students/:student_id/lessons', to: 'lessons#create'
#new
get 'students/:student_id/lessons/new', to: 'lessons#new', as: 'new_lesson'
#edit
get 'lessons/:id', to: 'lessons#edit', as: 'edit_lesson'
#update
patch 'lessons/:id', to: 'lessons#update', as: 'lesson'
#destroy
delete 'lessons/:id', to: 'lessons#delete'

# Assignment
#index
get 'lessons/:lesson_id/assignments', to: 'assignments#index', as: 'assignments'
#create
post 'lessons/:lesson_id/assignments', to: 'assignments#create'
#practice
get 'lessons/:lesson_id/practice', to: 'assignments#practice', as: 'practice'
#new
get 'lessons/:lesson_id/assignments/new', to: 'assignments#new', as: 'new_assignment'
#play
patch 'assignments/:id/play', to: 'assignments#play', as: 'played'
#edit
get 'assignments/:id', to: 'assignments#edit', as: 'edit_assignment'
#update
put 'assignments/:id', to: 'assignments#update', as: 'assignment'
#delete
delete 'assignments/:id', to: 'assignments#destroy', as: 'delete_assignment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :verify_teacher
  
  def index
  	@students = User.where(teacher_id: params[:teacher_id])
  end

  def show
  	@student = User.find(params[:id])
  end

  private

  def verify_teacher
  	if current_user.student?
  		redirect_to lesson_index_path(current_user)
  	end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/index.html.erb
<h2> My Students </h2>

<% @students.each do |student| %>
	<div class='row valign-wrapper'>
		<div class='col s12 m4 valign'>
			<h5> <%= link_to "#{student.first_name} #{student.last_name}", lessons_path(student) %> </h5>
		</div class='valign'>
		<div class='col s6 m4 valign'>
			<%= button_to "Student Information", show_student_path(student), method: :get, class: 'btn' %>
		</div>
		<div class='col s6 m4 valign'>
			<% if Lesson.where(user_id: student.id).exists? %>
				<%= button_to "Last Lesson", assignments_path(Lesson.where(user_id: student.id).order('lesson_date').last), method: :get, class: 'btn' %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/students/show.html.erb
<h1> <%= @student.first_name %> <%= @student.last_name %> Details </h1>

<p> <%= @student.age ? ("|| Age: #{@student.age}") : nil %> <%= @student.instrument ? ("|| Instrument(s): #{@student.instrument}") : nil %> </p>

<p> <%= @student.email %> </p>

<p> <%= @student.notes %> </p>

<% if current_user == @student %>
	<%= button_to 'Edit Information', edit_user_registration_path, method: :get, class: 'btn' %>
<% end %>