config/routes.rb
Rails.application.routes.draw do
root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

# Teacher
#show
get 'teachers/:id', to: 'teachers#show', as: 'show_teacher'

# Student
#show
get 'students/:id', to: 'students#show', as: 'show_student'
#index
get 'teachers/:teacher_id/students', to: 'students#index', as: 'student_index'

# Lesson
#index
get 'students/:student_id/lessons', to: 'lessons#index', as: 'lessons'
#create
post 'students/:student_id/lessons', to: 'lessons#create'
#new
get 'students/:student_id/lessons/new', to: 'lessons#new', as: 'new_lesson'
#edit
get 'lessons/:id', to: 'lessons#edit', as: 'edit_lesson'
#update
patch 'lessons/:id', to: 'lessons#update', as: 'lesson'
#destroy
delete 'lessons/:id', to: 'lessons#delete'

# Assignment
#index
get 'lessons/:lesson_id/assignments', to: 'assignments#index', as: 'assignments'
#create
post 'lessons/:lesson_id/assignments', to: 'assignments#create'
#practice
get 'lessons/:lesson_id/practice', to: 'assignments#practice', as: 'practice'
#new
get 'lessons/:lesson_id/assignments/new', to: 'assignments#new', as: 'new_assignment'
#play
patch 'assignments/:id/play', to: 'assignments#play', as: 'played'
#edit
get 'assignments/:id', to: 'assignments#edit', as: 'edit_assignment'
#update
put 'assignments/:id', to: 'assignments#update', as: 'assignment'
#delete
delete 'assignments/:id', to: 'assignments#destroy', as: 'delete_assignment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id          :integer          not null, primary key
#  lesson_date :date             not null
#  feedback    :text
#  notes       :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Lesson < ApplicationRecord
	belongs_to :user
	has_many :assignments, dependent: :destroy

	validates_presence_of :lesson_date

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :verify_teacher, except: [:index]
	before_action :student_by_id, only: [:index, :new, :create]
	before_action :lesson_by_id, only: [:edit, :update, :destroy]

  def index
  	@lessons = @student.lessons.order('lesson_date')
  end

  def new
  	@lesson = Lesson.new
  end

  def create
  	@lesson = @student.lessons.new(lesson_params)

  	if @lesson.save
  		redirect_to assignments_path(@lesson)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update

  	if @lesson.update(lesson_params)
  		redirect_to assignments_path(@lesson)
  	else
  		render :edit
  	end
  end

  	def destroy
  		@user = User.find(@lesson.user_id)
  		@lesson.destroy
  		redirect_to lessons_path(@user)
  	end

  	private

  		def lesson_params
  			params.require(:lesson).permit(:lesson_date, :feedback, :notes)
  		end

  		def student_by_id
  			@student = User.find(params[:student_id])
  		end

  		def lesson_by_id
  			@lesson = Lesson.find(params[:id])
  		end

      def verify_teacher
        if current_user.student?
          redirect_to lessons_path(current_user)
        end
      end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<% if @lesson.errors.any? %>
	<% @lesson.errors.full_messages.each do |error| %>
		<%= error %>
	<% end %>
<% end %>

<%= form_for @lesson do |f| %>
<div>
<%= f.label :lesson_date, for: 'date', class: 'active' %>
<%= f.date_field :lesson_date, id: 'date', class: 'datepicker' %>
</div>
<div class='input-field'>
<%= f.text_area :feedback, id: 'feedback', class: 'materialize-textarea' %>
<%= f.label :feedback, for: 'feedback' %>
</div>
<div class='input-field'>
<%= f.text_area :notes, id: 'notes', class: 'materialize-textarea' %>
<%= f.label :notes, for: 'notes'%>
</div>
<%= f.submit 'Submit', class: 'btn' %>

<% end %>

app/views/lessons/edit.html.erb
<h1>Lessons#edit</h1>

<%= render(partial: 'form') %>

app/views/lessons/index.html.erb
<h1>Lessons for <%= @student.first_name %> </h1>

<% @lessons.each do |lesson| %>

	<div class='card'><strong><%= lesson.lesson_date %></strong>
	
		<p>Notes: <%= lesson.notes %></p>

		<p>Feedback: <%= lesson.feedback %></p>
	</div>

	<% if current_user.teacher? %>
		<%= link_to 'Edit Lesson', edit_lesson_path(lesson), class: 'btn'%>
		<%= link_to 'Assignments', assignments_path(lesson), class: 'btn'%>
	<% end %>
	<hr>
	<% if current_user.student? %>
		<%= link_to 'Assignements', assignments_path(lesson) %>
	<% end %>
<br>
<% end %>
<% if current_user.teacher? %>
	<%= link_to 'Create Lesson', new_lesson_path(@student), class: 'btn' %>
<% end %>

<% if current_user.teacher? %>
	<%= link_to 'Students', student_index_path(current_user), class: 'btn' %>
<% end %>

<hr>

app/views/lessons/new.html.erb
<h1>Lessons#new</h1>

<%= render(partial: 'form') %>