config/routes.rb
Rails.application.routes.draw do
root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

# Teacher
#show
get 'teachers/:id', to: 'teachers#show', as: 'show_teacher'

# Student
#show
get 'students/:id', to: 'students#show', as: 'show_student'
#index
get 'teachers/:teacher_id/students', to: 'students#index', as: 'student_index'

# Lesson
#index
get 'students/:student_id/lessons', to: 'lessons#index', as: 'lessons'
#create
post 'students/:student_id/lessons', to: 'lessons#create'
#new
get 'students/:student_id/lessons/new', to: 'lessons#new', as: 'new_lesson'
#edit
get 'lessons/:id', to: 'lessons#edit', as: 'edit_lesson'
#update
patch 'lessons/:id', to: 'lessons#update', as: 'lesson'
#destroy
delete 'lessons/:id', to: 'lessons#delete'

# Assignment
#index
get 'lessons/:lesson_id/assignments', to: 'assignments#index', as: 'assignments'
#create
post 'lessons/:lesson_id/assignments', to: 'assignments#create'
#practice
get 'lessons/:lesson_id/practice', to: 'assignments#practice', as: 'practice'
#new
get 'lessons/:lesson_id/assignments/new', to: 'assignments#new', as: 'new_assignment'
#play
patch 'assignments/:id/play', to: 'assignments#play', as: 'played'
#edit
get 'assignments/:id', to: 'assignments#edit', as: 'edit_assignment'
#update
put 'assignments/:id', to: 'assignments#update', as: 'assignment'
#delete
delete 'assignments/:id', to: 'assignments#destroy', as: 'delete_assignment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeachMe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav>
    <div class="nav-wrapper">
      <%= link_to 'TeachMe', root_path %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li> <%= link_to 'Log Out', destroy_user_session_path, method: :delete %> </li>
	    <% if current_user.teacher? %>
	      <li> <%= link_to 'My Students', student_index_path(current_user) %> </li>
	      <li> <%= link_to 'My Information', show_teacher_path(current_user) %> </li>
	    <% else %>
	    <li> <%= link_to 'My Information', show_student_path(current_user) %> </li>
	      <li> <%= link_to 'My Current Assignments', assignments_index_path(Lesson.where(user_id: current_user.id).order('lesson_date').last) if Lesson.where(user_id: current_user.id).any? %> </li>
	      <% end %>
      <% else %>
      	<li> <%= link_to 'Sign In', new_user_session_path %> </li>
      	<li> <%= link_to 'Create Account', new_user_registration_path %> </li>
      <% end %>
      </ul>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>